### ISSUE TITLE
Error: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by przemyslaw0** [meejah/carml#58] opened 2023-11-08 15:44 UTC
I followed all the [instructions](https://carml.readthedocs.io/en/latest/installation.html) when I installed carml, but I get this error:

```
$ /home/user/.local/bin/carml --connect tcp:127.0.0.1:8002 -d -p 02akZrcW12xuvHcwSVUwlDLU circ --list
Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 700, in errback
    self._startRunCallbacks(fail)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 763, in _startRunCallbacks
    self._runCallbacks()
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 1750, in gotResult
    current_context.run(_inlineCallbacks, r, gen, status)
--- <exception caught here> ---
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/carml/cli.py", line 154, in _startup
    tor = await txtorcon.connect(reactor, ep)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/txtorcon/controller.py", line 462, in connect
    raise errors[0]
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/txtorcon/controller.py", line 456, in connect
    tor = yield try_endpoint(ep)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/txtorcon/controller.py", line 427, in try_endpoint
    config = yield TorConfig.from_protocol(proto)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/txtorcon/torconfig.py", line 584, in from_protocol
    yield cfg.post_bootstrap
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/home/user/.local/pipx/venvs/carml/lib/python3.11/site-packages/txtorcon/torconfig.py", line 1084, in _do_setup
    v = v[name]
builtins.TypeError: 'NoneType' object is not subscriptable
```

My Linux is Debian GNU/Linux [Trixie](https://wiki.debian.org/DebianTrixie) (testing) amd64, my Python version is 3.11.6.

The carml I installed is inside a venv.

**Comment by meejah** [comment] 2023-11-15 07:26
Hmm, I tried installing in a 3.11 venv on a Debian-derived PureOS byzantium and also on Debian bookworm system and it seems to work.

Given where the error is, this could be due to Tor version -- I have 0.4.8.6 and 0.4.8.7 (respectively) on the above two systems.

(Looking at the code, I'm really not sure how a `None` could ever be returned on that line ... but obviously it is happening!)

**Comment by meejah** [comment] 2023-11-15 07:27
Is there anything interesting about your Tor setup?

**Comment by meejah** [comment] 2023-11-20 06:12
Thanks, that does repeat the issue (with some modifications to the pasted torrc).

I believe this is related to https://github.com/meejah/txtorcon/issues/389 in txtorcon ... but the fix isn't in a release yet. I'll do one soon, but meantime you could test by installing via `pip install https://github.com/meejah/txtorcon/archive/refs/heads/main.zip` to get the latest txtorcon in your venv.

**Comment by meejah** [comment] 2023-11-20 09:38
New carml released as well .. please re-open this if the issue is not fixed for you!

**Closed by meejah** 2023-11-20 09:38 UTC

**Comment by meejah** [comment] 2023-11-20 17:04
thanks. that should definitely work, opened a new issue.
